# PHP practicals add more
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php


trigger:
- '*'

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'subscription-id'
  # Web app name
  webAppName: 'web-app-name'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'environment-name'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  variables:
    phpVersion: '7.2'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        archiveType: 'zip'
        includeRootFolder: false
        replaceExistingArchive: true
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName).$(Build.BuildId).zip'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        ArtifactName: 'drop'
        PathtoPublish: $(Build.ArtifactStagingDirectory)
  
    

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: PHP app'
            inputs:
              azureSubscription: 'Resource Manager - PHP website'
              appName: '$(WebAppName)'
              # package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
